/*********************************************************************************
 * file: common.js
 * date: 19 August 2015
 * Description: Menu navigation controller. This file will be included in all the
 * pages.
*********************************************************************************/

/*********************************************************************************
  * [ sesamiFactory ]
  * A function factory. It creates a closure envrionment and returns an object
  * which will later be attached to the menu button. The returned object has 
  * functions to display / hide the site navigation with animation effects 
  * when the menu button is clicked. The menu button ( a three-bar-navigation 
  * with Tux behid it ) is designed to be displayed when the screen size is 480px 
  * or less. For the details about the display mechanism, please refer to default.css.
  *
  * Arguments:
  * _targetEl - HTML DOM element object, namely, target for the css animation.
  * _keyframesOpen - Name of the animation used when menu is displayed.
  * _keyframesClose - Name of the animation used when menu is hidden.
  * _duration - animation-duration
  * _timingFunction - animation-timing-function
  * _fillMode - animation-fill-mode
  *********************************************************************************/
function sesamiFactory ( _targetEl, _keyframesOpen, _keyframesClose,
	_duration, _timingFunction, _fillMode ) {

	/*
		Private vairables. These variables are enclosed in the function environment,
		so can not be changed from outside the function context.
	*/
	/* Do not change these UPPERCASE variables. They are used as constants. */
	var STATUS_OPEN = "open";
	var STATUS_CLOSE = "close";
	/* As mentioned, the menu button is displayed when the screen size is 480px or less. */
	var SCREEN_WIDTH_THRESHOLD = 480;

	var targetEl = _targetEl;
	var keyframesOpen = _keyframesOpen;
	var keyframesClose = _keyframesClose;
	var status = STATUS_CLOSE;
	var duration = _duration || "1s";		// default value - 1s
	var timingFunction = _timingFunction || "linear";		// default value - linear
	var fillMode = _fillMode || "forwards";		// default value - forwards

	/*
	animation strings. They will be hooked on DOMElementObject.style.[webkit]animation.
	For this particular case, we need 2 animations, one for displaying menu, one for hiding 
	menu.
	*/
	var animationStringOpen = keyframesOpen + " " + duration + " " + timingFunction + " " + fillMode;
	var animationStringClose = keyframesClose + " " + duration + " " + timingFunction + " " + fillMode;

	/*
	Attach a function which nullifies the animation property to window.resize event.
	The user will ocasionally see the after-image when the screen size goes through the
	480px threshold.
	*/
	window.addEventListener (
		"resize",
		function () {
			var clientWidth = document.documentElement.clientWidth;
			if ( clientWidth > SCREEN_WIDTH_THRESHOLD ) {
				status = STATUS_CLOSE;
				targetEl.style.animation = targetEl.style.webkitAnimation = "";
			}
		},
		false
	);

	/*
	Returned object. switchSesami is the interface and attached to click event on the menu button.
	*/
	return {
		/*
		switchSesami - switches to the relevant function depending on the menu display status.
		*/
		switchSesami : function () {
			if ( status == STATUS_CLOSE ) {
				this.open ();
			}
			else {
				this.close ();
			}
			status = ( ( status == STATUS_CLOSE ) ? STATUS_OPEN : STATUS_CLOSE );
		},
		open : function () {
			targetEl.style.animation = animationStringOpen;
			targetEl.style.webkitAnimation = animationStringOpen;
		},
		close : function () {
			targetEl.style.animation = animationStringClose;
			targetEl.style.webkitAnimation = animationStringClose;
		}
	};
}


/*********************************************************************************
When window is loaded, we create two "instances" of the animation-effect 
function for displaying / hiding menu ( generated by sesamiFactory function ).
One for navigation menu ( ul element ), the other for the three line menu bar 
(html entity &#9776; / html id #opensesami ). Then, switchSesami function 
of each instance will be attached to click event on the three line menu bar.
*********************************************************************************/
window.addEventListener (
	"load",
	function () {
		/* three line menu bar */
		var sesami = document.querySelector ( "#opensesami" );

		/* please see the @keyframes rules in css */
		var sesamiFunc1 = sesamiFactory ( document.querySelector ( "#logo_area" ), "MonkeyOpen", "MonkeyClose", "0.25s", "ease-in-out", "forwards" );
		var sesamiFunc2 = sesamiFactory ( sesami, "KappaOpen", "KappaClose", "0.25s", "ease-in-out", "forwards" );

		/* onclick event */
		sesami.addEventListener (
			"click",
			function () {
				sesamiFunc1.switchSesami ();
				sesamiFunc2.switchSesami ();
			},
			false
		);
	},
	false
);
